spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰 命名转换为下划线命名
  ## 163邮箱配置
  mail:
    host: smtp.126.com
    username: andyhuua@126.com
    password: QPKSGPVCCHQFKRUB
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
    # rabbitmq 配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
lagou:
  mail:
    content:
      verifyCode:
        topic: 拉勾教育注册邮件通知3
        content: <h1>欢迎注册拉勾教育，您的注册验证码为：{{verifyCode}}, 祝您学习愉快!</h1>
